/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ApiPublicHooksRefreshAvailabilityRouteImport } from './routes/api/public/hooks/refresh-availability'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshAvailabilityRoute =
  ApiPublicHooksRefreshAvailabilityRouteImport.update({
    id: '/api/public/hooks/refresh-availability',
    path: '/api/public/hooks/refresh-availability',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/api/public/hooks/refresh-availability': typeof ApiPublicHooksRefreshAvailabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/api/public/hooks/refresh-availability': typeof ApiPublicHooksRefreshAvailabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/api/public/hooks/refresh-availability': typeof ApiPublicHooksRefreshAvailabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnostics' | '/api/public/hooks/refresh-availability'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnostics' | '/api/public/hooks/refresh-availability'
  id:
    '__root__' | '/' | '/diagnostics' | '/api/public/hooks/refresh-availability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ApiPublicHooksRefreshAvailabilityRoute: typeof ApiPublicHooksRefreshAvailabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-availability': {
      id: '/api/public/hooks/refresh-availability'
      path: '/api/public/hooks/refresh-availability'
      fullPath: '/api/public/hooks/refresh-availability'
      preLoaderRoute: typeof ApiPublicHooksRefreshAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ApiPublicHooksRefreshAvailabilityRoute:
    ApiPublicHooksRefreshAvailabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
